vechain/thor

cmd/thor/node/node.go
NTP Server ap.pool.ntp.org does not exist, so thor node cannot check NTP time.
=> Update NTP Server in node.go

genesis/customnet.go
golangci-lint said:
`genesis/customnet.go:38:5: SA4003: unsigned values are never < 0 (staticcheck)`
`if gen.GasLimit < 0 {
return nil, errors.New("gasLimit must not be 0")
}`
Seems like a typo for me.
=> Typo in if statement

vm/README.md, vm/evm.go, vm/gas_table.go, vm/instructions.go, vm/instructions_test.go, vm/jump_table.go, vm/memory.go, vm/memory_table.go, vm/opcodes.go, vm/patch.go
Upgraded EVM from v1.8.14 to v1.8.27
Features:
- opcode `create2`
- opcode `extcodehash`
Not implemented:
Due to dependency limitation, some features require a mass scale of dependency change, which is not implemented. See `vm/README.md`.
Solo Testing:
Test code: [thor-create2-test](https://github.com/laalaguer/thor-create2-test) 
- `create2` external test passed. 
- `extcodehash` external test passed.
Testnet Testing:
- `testnet` syncing test passed till latest.
=> added opcode, not activated

api/accounts/accounts.go, api/blocks/blocks.go, api/blocks/types.go, api/transactions/transactions.go, chain/block_reader_test.go, chain/cache.go, chain/chain.go, chain/chain_test.go, chain/persist.go, chain/repository.go, chain/repository_test.go, cmd/thor/pruner/pruner.go, cmd/thor/sync_logdb.go, comm/announcement_loop.go, consensus/consensus.go
- introduce BlockSummary for block header persistence
- store one tx/receipt per record instead of bundle
- optimize tx/receipt cache
- optimize /blocks query API (without need to query block body)
=> chain: improve tx/receipt persistence

cmd/thor/node/packer_loop.go
fix a minor bug that in rare case the master node will ignore better block, when receives two or more blocks with same number almost at the same time.
=> thor/node: improve pack loop

cmd/thor/utils.go
to prevent from breaking the full-archived state when accidentally starting the node without `--disable-pruner` flag.
=> feat: isolate the full-archived data dir from state-pruned

cmd/thor/utils.go
the channel used with signal.Notify should be buffered (SA1017)
os.Kill cannot be trapped (did you mean syscall.SIGTERM?) (SA1016)
should use a simple channel send/receive instead of select with a single case (S1000)
=> cmd(thor): improve handle exit signal

go.mod, go.sum
upgrade crypto/secp256k1
```
benchstat before.txt after.txt                                                                                                        
name       old time/op    new time/op    delta
Sign-8       69.0µs ± 1%    37.0µs ± 1%  -46.28%  (p=0.008 n=5+5)
Recover-8     119µs ± 1%      54µs ± 1%  -54.43%  (p=0.008 n=5+5)
```
=> deps: replace go-ethereum dependency with the fork under vechain

lowrlp/encoder.go, state/state.go, trie/fast_node_encoder.go, trie/hasher.go, trie/iterator.go, trie/node.go, trie/node_test.go, trie/proof.go
In this PR, lowrlp.Encoder is not pooled, instead the encoder is cached in hasher object( saves pool.Get/Put callings).
benchmarks:
```bash
$ benchstat before.txt after.txt 
name                  old time/op  new time/op  delta
FastEncodeFullNode-8   216ns ± 1%   180ns ± 0%  -16.97%  (p=0.008 n=5+5)
```
=> Faster trie node encode

go.mod, go.sum
* improve manifest file size limit
* optimize merged iterator again
* reduce compaction table set of target level
* improve memdb
=> deps: upgrade goleveldb

thor/fork_config.go
Scheduled FORK at **～ Fri, 19 Aug 2022 08:00:00 GMT** 
*Precisely scheduled at Fri, 19 Aug 2022 07:42:30 GMT, depending on the network*
=> schedule testnet finality fork

Dockerfile
docker runs the node though a new `thor` user, following [the slowmist security guidelines](https://github.com/slowmist/vechain-core-nodes-security-checklist/blob/master/README-en.md#23-avoid-using-root-to-run-thor), instead of the current implementation, which runs it under `root`
=> docker container runs thor under new user

api/api.go, api/debug/debug.go, api/debug/types.go
This PR is on top of #600, added API `POST /debug/tracers/call` which is equivalent to `eth_debugTraceCall`, allowing users to do a trace while evaluating a contract call. #589 initiated the feature request.
=> Add tracer API for evaluating a contract call

cmd/thor/flags.go, cmd/thor/node/packer_loop.go
Salute to Apple's New 8GB MacBook Pro.
=> cmd/thor: set default cache size to 4GB

consensus/consensus_test.go
This PR closes [this issue](https://github.com/vechainfoundation/protocol-board-repo/issues/27) by increasing the coverage of all files above 80%
=> Add consensus tests

.github/workflows/test.yaml, .gitignore, Makefile
Also added go 1.21.x to GitHub action flow
=> ci: integrate codecov

.github/workflows/close-stale-issues.yaml
These changes mark issues and PRs with a `stale` tag and auto closes them 7 days later if not action is taken.
N/A
N/A
=> adding an action to tag and auto close issues and PRs if stale

poa/candidates_test.go
This PR adds tests to `poa/candidates`. The code coverage exceeds the 80% target.
@libotony 
A question that i have is about the `func (c *Candidates) Copy() *Candidates` which doesn't seem to perform a deep copy. Is it intentional?
Fixes # [Code Coverage :: poa#30](https://github.com/vechainfoundation/protocol-board-repo/issues/30)
`make test-coverage`
=> Adds poa/candidate tests

genesis/customnet_test.go, genesis/devnet_test.go, genesis/genesis_test.go, genesis/mainnet_test.go
This PR addresses this [issue](https://github.com/vechainfoundation/protocol-board-repo/issues/22), by including test cases that increase the genesis coverage from an initial
builder   -> 80%
customnet -> 0%
devnet    -> 0%
genesis   -> 60%
mainnet   -> 0%
testnet   -> 70.6%
to 
builder   -> 90%
customnet -> 75%
devnet    -> 75.7%
genesis   -> 73.3%
mainnet   -> 76.4%
testnet   -> 70.6%
The lack of 80% coverage across all files is due to the fact that some parts of the code are unreachable. For example see the below snippet. To my understanding we are setting some global hardcoded values to the state and we have some error checking code. Since the value is constant and valid, the error case is never executed thus showing up as uncovered code. 
```golang
// setup builtin contracts
if err …
```
=> Add genesis tests to increase coverage

builtin/energy/energy_test.go
This PR addresses this [issue](https://github.com/vechainfoundation/protocol-board-repo/issues/31). Tests have been added for `energy.go` to increase coverage from 49.15 to 79.7%. The reason for not having above 80% coverage is uncoverable code. For example see the snippet below:
```golang
func (e *Energy) getInitialSupply() (init initialSupply, err error) {
err = e.state.DecodeStorage(e.addr, initialSupplyKey, func(raw []byte) error {
if len(raw) == 0 {
init = initialSupply{&big.Int{}, &big.Int{}, 0}
return nil
}
return rlp.DecodeBytes(raw, &init)
})
return
}
```
In the snippet above we want to cover the path inside the `if len(raw) == 0` path. The issue is that this is only (to my understanding) affected by the `initialSupplyKey` which is hardcoded and cannot be passed as argument. …
=> Add builtin tests

cmd/thor/node/master_test.go, cmd/thor/node/stats_test.go, cmd/thor/node/worker_test.go
Adding tests to increase coverage of `master.go`, `stats.go` and `worker.go` over 80%. This PR addresses the following [issue](https://github.com/vechainfoundation/protocol-board-repo/issues/18).
=> Add cmd tests to increase coverage

.github/workflows/test.yaml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
When unit tests fail on main branch send slack notification to team
Also adjusted the workflow to only run matrix job of unit tests on PR and push to main
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
Sample request to slack channel
=> slack notification

runtime/runtime_test.go
`runtime.go` from 39.13% to 75%
Addresses [#29](https://github.com/vechain/protocol-board-repo/issues/29)
=> Increase runtime package coverage to 75%

trie/derive_root_test.go
Adds a test for DeriveRoot function of the trie package
Adds a test for DeriveRoot using a self generated KAT(Known Answer Test). Given that our implementation differs only in the hash function from Ethereum we assume its correctness.
`make test`
* Go Version: 1.21.8
* Hardware: darwin/amd64
* Docker Version: -
=> Adds test for DeriveRoot function in trie

api/subscriptions/types_test.go
Changed TestConvertBlockWithBadSignature to always use the same broken signature instead of randomly generating a sig on-the-fly
* Go Version:
* Hardware:
=> Fix flaky test - TestConvertBlockWithBadSignature

runtime/runtime_test.go, thor/fork_config_test.go, vm/jump_table_test.go
This PR integrates some tests for the Shanghai version. In details:
- basefee: takes the [EIP-3198](https://eips.ethereum.org/EIPS/eip-3198) test cases to isolate the basefee opCode pre and after shanghai fork activation;
- contract starting with 0xEF: takes the [EIP-3541](https://eips.ethereum.org/EIPS/eip-3541) test cases; tested pre and after shanghai fork activation;
- push0: unit test checking a zero value is pushed on top of the stack.
=> test: add tests for shanghai new opcodes

api/doc/stoplight-ui/index.html, api/doc/swagger-ui/index.html
Changes API docs to use absolute links instead of relative links, as they break with a proxy
Start a proxy and visit the node docs
=> fix: relative links don't work with a proxy

cmd/thor/flags.go, cmd/thor/main.go, cmd/thor/solo/solo.go, cmd/thor/solo/solo_test.go, docs/usage.md
Tackles the following [issue](https://github.com/orgs/vechain/projects/22/views/1?filterQuery=label%3A%22App%3A+Thor%22%2C%22App%3A+VIP%22%2C%22App%3A+Thorest%22++solo&pane=issue&itemId=53228366). In this PR I basically added the option to use a command-line argument specifically for solo to allow the developer to choose a custom block interval with a minimum value of 1. I tested it and it looks like its working fine for 1 second block intervals as well as larger intervals like 100 seconds.
=> Selectable block interval on solo

.github/workflows/lint-go.yaml
This is weird one.
1. Linter should be failing for both [PR](https://github.com/vechain/thor/actions/runs/9227306033/job/25388962083) and [Master](https://github.com/vechain/thor/actions/runs/9227356106/job/25389300810). But it only fails in [Master](https://github.com/vechain/thor/actions/runs/9227356106/job/25389300810).
2. When one emulates what github does: `docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.54.2 golangci-lint run -v` it fails with:
```
state/state.go:515:40: G601: Implicit memory aliasing in for loop. (gosec)
if err := saveAccount(trieCpy, addr, &c.data, &c.meta); err != nil {
^
vm/instructions_test.go:223:2: G101: Potential hardcoded credentials (gosec)
y := "a1f5aac137876480252e5dcac62c354ec0d42b76b0642b6181ed099849ea1d57"
^ …
```
=> Update linter to 1.55

api/subscriptions/subscriptions_test.go
We've had multiple failing tests in ci/cd caused by a timeout while running the subscriptions tests. The issue is not directly reproducible locally and failing runs happen randomly, but the issue seems to be related to the websocket connection not being able to receive a message, so it hangs waiting indefinitely. This PR adds a timeout of 5 seconds: if a message is not received the test is simply skipped.
Fixes [issue-199](https://github.com/vechain/protocol-board-repo/issues/199)
=> remove flaky subscription test

api/doc/doc.go, api/doc/doc_test.go, go.mod, go.sum
This PR has two changes to the dependency:
+ Bumped `google.golang.org/protobuf` to v.1.33.0 to eliminate #752 
+ Use `gopkg.in/yaml.v3` instead of v2 to share the same one of indirect dependency, added test case to ensure the use case
=> tidy dependency

api/accounts/accounts.go, api/api.go, api/blocks/blocks.go, api/debug/debug.go, api/events/events.go, api/metrics.go, api/metrics_test.go, api/node/node.go, api/subscriptions/subscriptions.go, api/transactions/transactions.go, api/transfers/transfers.go, api/utils/http.go, cmd/thor/flags.go, cmd/thor/main.go, go.mod, go.sum
Using middleware to capture HTTP server metrics, added names for all paths, added feature that only records named path's metrics to avoid random API access potentially blowing up metrics db.
In this PR, **dependency upgraded** `github.com/gorilla/mux` v1.6.0 -> v1.8.1
=> use middleware to capture HTTP server metrics

api/subscriptions/subscriptions_test.go
This PR reintroduce the pending subscription test previously deleted because flaky.
Fixes # [issue-214](https://github.com/vechain/protocol-board-repo/issues/214)
=> Fix and re-add subscription test

.github/workflows/go-mod-check.yaml, .github/workflows/on-master-commit.yaml, .github/workflows/on-pull-request.yaml, go.mod
This is a test run on top of our current master branch https://github.com/libotony/thor/actions/runs/9298578314/job/25590743272
=> add workflow for go module check

Makefile
Fix make thor when 2 tags exist
=> fix: tag returns 2 results when latest RC equals official release

api/subscriptions/subscriptions_test.go
Removing the pending tx subscription test since it's already covered in e2e test suite.
=> Remove pending tx test since test case already covered in e2e

cmd/thor/flags.go, cmd/thor/main.go, cmd/thor/utils.go
allow injection of master key via stdin
Run:
```bash
echo "842497a1c69577f4be27ae2ec64751a0c0165f9011e6c27570e21f48c4af9d50" | ./bin/thor --network=main --master-key-stdin
```
=> feat: allow injection of master key via stdin

.github/workflows/test-e2e.yaml, api/api.go, api/events/events.go, api/events/events_test.go, api/events/types.go, api/transfers/transfers.go, api/transfers/transfers_test.go, cmd/thor/flags.go, cmd/thor/main.go, docs/usage.md, logdb/logdb.go, logdb/logdb_test.go
Add a flag to allow node runner to specify the logs limit for the logs filter API.
* Go Version:
* Hardware:
=> add api-logs-limit flag

block/header.go, cmd/thor/bandwidth/bandwidth_test.go
Increases `bandwith.go` coverage to 84%. Relevant [issue](https://github.com/vechain/protocol-board-repo/issues/184).
=> Increase bandwidth coverage

cmd/thor/flags.go, cmd/thor/main.go, cmd/thor/utils.go
This is a minor improvement of the flags parsing component.
=> use uint64 for number flags

api/accounts/accounts.go, api/blocks/blocks_test.go, api/debug/debug.go, api/debug/debug_test.go, api/utils/revisions.go, api/utils/revisions_test.go
Small refactor around getsummary
* Go Version:
* Hardware:
=> getsummary and getsummaryAndState decoupling

api/metrics.go, api/metrics_test.go
Previously, we had several failed CI runs on the test of web socket connection metrics.  This PR had removed close conn test which are failing in the GH action (succeeds on local).
=> api: remove websocket conn close test

Dockerfile, api/debug/debug.go, api/debug/debug_test.go
In the API doc, it is describing `The maximum number of results to be returned. Default is 1000.` for the option `maxResult`, but the feature wasn't implemented in the code.
=> api: fix max result in debug trace storage

cmd/thor/flags.go, cmd/thor/main.go, docs/usage.md
This PR makes the already existing flags 
- `txpool-limit-per-account` (default 16)
- `txpool-limit` (default 10k)
which were previously solo only flags available in testnet and mainnet modes. No unbounded option was added but we can discuss if that is necessary.
=> Add cli option for limit-per-account in the mempool

.github/workflows/test-e2e.yaml, api/api.go, api/debug/debug.go, api/debug/debug_test.go, api/doc/thor.yaml, cmd/thor/flags.go, cmd/thor/main.go, cmd/thor/utils.go, docs/usage.md, tracers/logger/logger.go, tracers/logger/logger_test.go, tracers/tracers.go
This is a tentative PR with regard to https://github.com/vechain/protocol-board-repo/issues/292
- Adds a new `allowed-tracers` flag. Ex: `--allowed-tracers="all"`, `--allowed-tracers="call,4byte"
- The default available tracers are changed - `--allowed-tracers="none"` is the default
- Node operator can now pick-and-choose which tracers are available
- "" is no longer accepted as a valid (defaulted to log) tracer name
Fixes # https://github.com/vechain/protocol-board-repo/issues/292
=> Add api-allowed-tracers flag

api/api.go, api/debug/debug.go, api/debug/debug_test.go, api/doc/thor.yaml, cmd/thor/main.go
There's a small bug when starting thor solo with a different genesis. PoA is still in use when the genesis is different from devnet genesis.
This fixes it by changing the PoA use check.
To replicate issue: 
```
curl -X GET http://localhost:8669/blocks/1
{"number":1,"id":"0x00000001a054ddd4f2297c4476670a4cb7f877658dcde2f96977bf9c28faf5cf","size":548,"parentID":"0x0000000008602e7a995c747a3215b426c0c65709480b9e9ac57ad37c3f7d73de","timestamp":1724420473,"gasLimit":40000000,"beneficiary":"0xf077b491b355e64048ce21e3a6fc4751eeea77fa","gasUsed":23405,"totalScore":1,"txsRoot":"0x956359ee97d46c0f7dfed2b2a9972778329b613d98fb57c6e98d293b8571b516","txsFeatures":1,"stateRoot":"0xd56b8cb8e15a668db8c971caeb96924f283e1c3c532823d74e85617bdaaa3255","receiptsRoot":"0x9007c0410c0b67afb8455b10853f7c85c829b38e21 …
```
=> Debug thor solo with different genesis

.github/workflows/test-e2e.yaml, api/api.go, api/debug/debug.go, api/debug/debug_test.go, api/doc/thor.yaml, cmd/thor/flags.go, cmd/thor/utils.go, tracers/logger/logger.go, tracers/tracers.go
- Make custom tracer work with allowed tracers
- Rename `logger` tracer to `structLoggerTracer` and remain backward compatiability
=> make custom tracer to work with allowed tracers flag

cmd/thor/sync_logdb.go, comm/comm_test.go, comm/communicator.go, comm/sync.go, comm/txs_loop.go
This PR is an improvement on top of PR #837, leveraging https://go.dev/blog/loopvar-preview
=> adopt loop var scope in go 1.22

api/debug/debug.go, api/subscriptions/subscriptions_test.go
This adds a test for the Subscriptions blocks Backtrace.
It allows moving the test from e2e into integrations.
=> Adding Test for Subscription Blocks Backtrace

.github/workflows/gosec.yaml, .github/workflows/lint-go.yaml, .golangci.yml, cache/rnd_cache.go, cmd/thor/solo/solo.go, comm/peer.go, p2psrv/rpc/rpc.go, test/datagen/numbers.go, txpool/tx_pool.go
Add new workflow for gosec when creating PRs to master and when merging into master.
[GH Issue](https://github.com/vechain/protocol-board-repo/issues/310)
=> Add new gosec gh yaml file

txpool/tx_object.go
+ Allow TX valid on next block to propagate.(eg. head at 19, TX with ref 20)
+ Stops propagate TX that is expired on next block.
=> pool:check executable against next block number

runtime/resolved_tx.go, runtime/resolved_tx_test.go, runtime/runtime.go, txpool/tx_object.go, txpool/tx_object_map.go, txpool/tx_object_map_test.go, txpool/tx_pool.go, txpool/tx_pool_test.go
Addresses vechain/protocol-board-repo#311
=> pool: track pending cost per payer

.github/workflows/test-e2e.yaml
Remove AWS Codebuild for the e2e as it's not needed anymore and costs money
=> chore: remove aws codebuild

api/doc/thor.yaml
As per title.
* Go Version:
* Hardware:
=> Update doc for default tracer

.github/workflows/publish-docker-images.yaml
Use different trivy image for docker scanning: [public.ecr.aws/aquasecurity/trivy-db:2](https://github.com/aquasecurity/trivy/discussions/7538)
=> fix(docker): using AWS docker repo for trivy

cmd/thor/node/node.go, cmd/thor/node/packer_loop.go, comm/handle_rpc.go, comm/sync.go, p2psrv/server.go, txpool/tx_pool.go
Leverage the trace log level so we can enable `Debug` without getting spammed with logs.
```bash
make thor
./bin/thor --network main --verbosity 4
```
Restarting a node that is nearly synced before starting:
Starting a node with a lot of blocks to sync:
=> enhancement(logging): leverage trace level

logdb/logdb.go
This PR fixes a bug where a client requests a large `to` in logs filters
=> fix: set range.To to max logDB block

api/events/types.go, logdb/logdb.go, logdb/sequence.go, logdb/sequence_test.go
Modifies the `ConvertFilter` method to take into account that the max block byte space is of 28 bytes instead of 32.
Now returns error if a direct access to the DB requests more than `blockNumMask`
=> Update Convert Filter to match BlockMask bit space

muxdb/cache.go, muxdb/metrics.go
Covers the metrics for cache hit/miss for root and node cache. In the diagram below:
1. Yellow line is a hit for the root one (in-memory representation of the trie)
2. Green line is a hit for a node one
3. Blue one is a miss for a node one
4. Red one is a miss for the root one
The formula in Grafana is `rate(thor_metrics_cache_hit_miss_count[$__rate_interval])`
=> Metrics: Cache hit/miss

README.md, api/doc/README.md, docs/CONTRIBUTING.md, docs/hosting-a-node.md, docs/usage.md
- Fix broken link
- Use absolute links
=> fix(documentation): use absolute links in markdown

muxdb/cache.go, muxdb/metrics.go
After a conversation with @libotony in a previous PR, creating this one so we get the metrics data at the same pace as we log the hit rate.
1. Raw hit/miss by number
- Yellow line: Root node hit rate
- Green line: Other trie node hit rate
- Orange line: Root node miss rate
- Blue line: Other trie node miss rate
2. Rate in percentage (hits over lookups)
- Yellow line: Root trie node
- Green line: Other trie node
=> Metrics: Reuse `shouldLog` so we get cache hit/miss data at the same pace

metrics/noop.go, metrics/prometheus.go
Collecting Disk I/O data (reads and writes only, not bytes for now) every 5 seconds. In the following graph we are applying `rate` as usual (please suggest any other representation).
If you want to reproduce it on your side, run it with Docker (the code assumes that your are running `thor` in Linux - I have a macOS - , use your local `data` folder):
```
docker run -d\
-v /Users/miguel_rojo/.org.vechain.thor:/home/thor/.org.vechain.thor\
--network thor-node-monitoring_monitoring\
-p 127.0.0.1:8669:8669 -p 11235:11235 -p 11235:11235/udp -p 127.0.0.1:2112:2112\
--name thor-node thor-local --network test --metrics-addr 0.0.0.0:2112 --enable-metrics
```
1. Yellow line: Writes
2. Green line: Reads
Some logs (not part of the current code, follow `LLEGA`):
```
INFO [11-22|12:50:36.538] LLEGA …
```
=> Metrics: Disk IO reads and writes

thorclient/httpclient/client.go, thorclient/thorclient.go, thorclient/wsclient/client.go, thorclient/wsclient/client_test.go
Make thorclient more configurable
=> chore: make thorclient configurable + fix type error

api/blocks/blocks.go, api/blocks/blocks_test.go, api/blocks/types.go, api/doc/thor.yaml, api/utils/http.go
This PR adds a `raw` query parameter to the `/blocks` endpoint, which returns RLP encoded block.
=> add 'raw' query parameter to the blocks

api/debug/debug.go, api/debug/debug_test.go, api/doc/thor.yaml
Currently if we want to trace one transaction, we need to provide a block id and txhash, but sometimes we only have txhash, so need to fetch the blockid first and then we can use this API. But actually we can fetch the blockid from txmeta, so this will simplify the client's logic.
* Go Version:
* Hardware:
=> feat(api/debug): support debug trace without blockId

cmd/thor/utils.go
Due to the previous implementation, when creating `metrics` in `state` the value was initialised to `noop` rather than `prometheus` since Devnet was initialising the State before Prometheus was set as metrics provider via `enable-metrics` in the command line.
It has been tested though the creation of metrics in the `state` package.
* Go Version: 1.23.3
* Hardware: macOS Sequoia
* Docker Version: 20.10.17
=> fix: Get Devnet ID after the Thor flags are set

.github/workflows/publish-docker-images.yaml
Adding attestations as per https://docs.docker.com/scout/policy/#supply-chain-attestations when publishing in Docker Hub.
Partially addresses https://github.com/vechain/protocol-board-repo/issues/360
=> chore: docker attestations

thorclient/api_test.go, thorclient/httpclient/client.go, thorclient/httpclient/client_test.go, thorclient/thorclient.go
This includes some fixes to thorclient.
=> Fixes to thorclient

chain/cache.go, chain/metric.go, chain/repository.go, muxdb/internal/trie/cache.go, muxdb/internal/trie/metrics.go, runtime/runtime.go, thor/cachestats.go, thor/cachestats_test.go
This PR moves cachestats to a standalone file to make it available globally and applies cachestats to muxdb and chain to track cache miss/hit. 
A notable change here is this PR changes the metric type in package chain to `GaugeVec`
* Go Version:
* Hardware:
=> extract cachestats to record cache stats 

api/accounts/accounts.go, api/metrics.go, api/subscriptions/pending_tx_test.go, api/subscriptions/subscriptions.go, api/subscriptions/subscriptions_test.go, api/utils/http.go, thorclient/common/common.go, thorclient/wsclient/client.go
This ticket refactors the `handlesubject` into the `websocked` method.
Fixes # [(issue)](https://github.com/vechain/otherviews-workboard/issues/115)
=> Refactor the subscriptions api to meet standard mount approach

.github/workflows/test.yaml, Makefile
Add go1.23 on Ubuntu tests and set Makefile to test minimum go version to go1.22.
=> add go1.23 on ubuntu tests

.github/workflows/test-e2e.yaml
GH actions config so e2e tests run on the `release/*` branches on the `thor-e2e-tests` repo.
[Example of execution using `release/galactica` on both repos](https://github.com/vechain/thor/actions/runs/12791470289/job/35659774316?pr=946) for pull requests (tests yet to be adapted, that is why the Shanghai tests are the only ones failing).
=> feat: e2e tests on release branches

.github/workflows/test-e2e.yaml
e2e tests config cherry-picked (to be merged once the tests are adapted)
=> chore(galactica): e2e tests config cherry-picked

docs/v2-2-0-migration-guide.md
=> chore(maindbv4): add a migration guide

metrics/telemetry.go, muxdb/metrics.go, muxdb/muxdb.go
This PR makes sure that we just call the db to get stats if the metrics are enabled (so different to noop).
=> Metrics (Compaction): Do not call the DB if metrics are disabled

txpool/tx_pool_test.go
Minor fix for flaky test, instead of waiting on housekeeping function, wash is invoked from the test and executable transactions are stored
* Go Version:
* Hardware:
=> Fix expired txs flaky test

.github/workflows/test.yaml
Only run CodeCove on `vechain/thor` & update codecov action to v5
=> chore(gha): only run codecov on vechain/thor

api/fees/fees.go, api/fees/fees_test.go
Added a couple of error messages missing due to relying on `err` (there is no `err` in those cases).
Added a test too.
=> fix(fees/history): missing error messages

api/doc/thor.yaml, api/fees/data.go, api/fees/fees.go, api/fees/fees_test.go, api/fees/types.go
This endpoint is a version of `eth_maxPriorityFeePerGas`. 
Interface-wise is the same, and the parameters are based on go-ethereum except for the max priority fee cap (500 gwei in Eth, we do not have a reference figure yet). The other difference is that all the params are internal and non-configurable (in geth they use also flags, we can do the same but I prefer to comment it over the PR).
Re-uses the cache logic of the other `fees` endpoint so the common cache is built by any of these endpoints.
Added a new integration test for this endpoint, further testing will be done as part of the follow-up ticket regarding parameters. Checked though that the priority fees array is built as expected.
Closes https://github.com/vechain/protocol-board-repo/issues/390
=> feat: `fees/priority` endpoint

api/blocks/blocks_test.go, api/blocks/types.go, api/doc/thor.yaml, api/transactions/transactions_converter.go, api/transactions/transactions_coverter_test.go, api/transactions/transactions_test.go
This PR returns the `baseFee`, `maxFeePerGas`, `maxPriorityFeePerGas` as hex values in `/transactions` and `/blocks` api endpoints response.
[GHIssue](https://github.com/vechain/protocol-board-repo/issues/440)
=> BaseFee, maxFeePerGas and maxPriorityFeePerGas as hex

cmd/thor/node/packer_loop.go, packer/packer.go
Moved the log stating galactica activation after a block is packed
=> refactor: move log printing galactica activation

consensus/fork/galactica.go, consensus/fork/galactica_test.go, consensus/validator.go, consensus/validator_test.go, packer/flow.go, packer/flow_test.go, runtime/runtime.go, runtime/runtime_test.go, txpool/tx_pool.go, txpool/validation.go, txpool/validation_test.go
When adopting a tx previously accepted in the mempool when the `baseFee` is higher was causing the tx to be removed from the mempool. Now it's just ignored because it's not adoptable now
=> Don't remove tx if non adoptable because baseFee too high

runtime/runtime.go, vm/chain_config.go, vm/contracts.go, vm/evm.go, vm/interpreter.go
This PR reverts name changes in vm package to kept shanghai as it's a evm version.
=> vm: keep shanghai as a version name

.github/workflows/go-mod-check.yaml, .github/workflows/gosec.yaml, .github/workflows/lint-go.yaml, .github/workflows/test.yaml, Dockerfile, Makefile, go.mod
Required: Install go v1.23 and golangci-lint@v1.64.5
To install latest linter:
```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
```
=> chore: update go and lint versions

cmd/thor/flags.go, cmd/thor/utils.go
Resolve URLs when starting a node
1. Solo
```bash
go run ./cmd/thor solo --genesis https://raw.githubusercontent.com/vechain/thor-e2e-tests/refs/heads/main/network/config/genesis.json
```
2. Custom Network
```
go run ./cmd/thor --network https://raw.githubusercontent.com/vechain/thor-e2e-tests/refs/heads/main/network/config/genesis.json  
```
=> feat: resolve url genesis

consensus/consensus_test.go, txpool/tx_pool_test.go
This PR adds two more tests for galactica:
- validate a malicious proposed block with a fake baseFee;
- adding a tx with the highest priority fee makes it first in line;
- adding a tx with the lowest priority fee makes it the last one.
=> Add more baseFee and validation tests

tx/builder.go, tx/builder_test.go, tx/transaction.go, tx/transaction_test.go, tx/tx_dynamic_fee.go, tx/tx_legacy.go
This PR includes several minor improvements to tx package:
- Make `legacyTransaction`, `dynamicFeeTransaction` and `txData` private
- Align with latest go-ethereum decodeRLP func
- Count type byte in `tx.Size()`
=> minor tx improvement

api/blocks/blocks_test.go, api/blocks/types.go, api/doc/thor.yaml, api/fees/fees.go, api/fees/fees_test.go, api/fees/types.go, api/transactions/transactions_converter.go, api/transactions/transactions_coverter_test.go, api/transactions/transactions_test.go, api/transactions/types.go, api/transactions/types_test.go, thorclient/api_test.go, thorclient/httpclient/client_test.go
This PR renames the base fee value to `baseFeePerGas` when exposed via api
[GHIssue](https://github.com/vechain/protocol-board-repo/issues/489)
=> Rename baseGas to baseFeePerGas as per VIP

api/doc/thor.yaml, api/transactions/transactions_converter.go, api/transactions/transactions_coverter_test.go, api/transactions/transactions_test.go
Do not return gas price coef for dynamic fee transaction in API server.
=> api: do not return gas price coef for dynamic fee transaction

api/utils/revisions.go, api/utils/revisions_test.go
The `next` block should not have the `best` transactions since they are not part of it.
=> fix: `next` block adjustments (transactions, gas used, receipts root)

block/extension.go, block/header.go, block/header_test.go, test/datagen/numbers.go, tx/transaction_test.go
Signing fields are defined to all fields, except the signature, we are writing these codes manually, to avoid any potential human error like [this](https://github.com/vechain/thor/pull/1020/commits/fa71fc0307f4121b37b6cc59283c50c25481372a), this PR introduced a reflect based singing hash test mechanism to run the signing in an automated way in the tests to have a guard for that kind of functions.
Links to vechain/protocol-board-repo#513
=> enhance tests for signing hashes, implemented a guard

Makefile, block/block_fuzz_test.go, block/block_test.go, block/header_test.go, tx/transaction_fuzz_test.go, tx/transaction_test.go
This PR adds some extra fuzz decode tests and improved fuzz command in Makefile which allows custom fuzz time via `make fuzz FUZZTIME=10m`
=> add decode fuzz tests for block, tx and receipt

consensus/fork/galactica.go, consensus/fork/galactica_test.go, consensus/validator_test.go
Title is self-explanatory. Also reviewed the checks at `txpool/validation.go` but I think the errors are good there since both tx fee values are 0 in those cases for legacy tx.
Closes https://github.com/vechain/protocol-board-repo/issues/537
=> feat(legacy tx): error message when base fee is greater than baseGasPrice

api/doc/thor.yaml
Also removed `required` for `newestBlock` since it is `best` when not provided
=> fix(`fees/history`): updated swagger docs so `newestBlock` can be `next`

api/doc/thor.yaml
Alignment with the actual field in the response
=> fix(`fees/history`): `gasUsedRatio` in Swagger

.github/workflows/go-mod-check.yaml, .github/workflows/gosec.yaml, .github/workflows/lint-go.yaml, .github/workflows/test.yaml, Dockerfile, Makefile, go.mod, log/format_test.go, log/logger_test.go, logdb/logdb_bench_test.go, muxdb/cache_test.go, thor/hash_test.go, tracers/tracers_test.go, trie/derive_root_test.go, trie/encoding_test.go, trie/node_test.go, trie/trie_test.go, tx/transaction_test.go, vm/analysis_test.go, vm/contracts_test.go, vm/instructions_test.go, vrf/vrf_test.go
```bash
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
```
=> chore: update go to 1.24

Makefile
=> Makefile: use macro to define the minimum required go version

api/transactions/transactions_test.go, api/utils/revisions_test.go, genesis/devnet.go, test/testchain/chain.go
Testchain now uses the devnet with the local timestamp.
This is particularly important to handle tx pool tests where the `isChainSynced` is used to determine the tx evaluation flow.
Previously the testchain was never sync'd, now it's always sync'd.
Fixes # [(issue)](https://github.com/vechain/otherviews-workboard/issues/157) and [issue](https://github.com/vechain/protocol-board-repo/issues/542)
=> Modify testchain to accept current time

consensus/consensus_test.go, genesis/builder.go
Avoids panic if a custom net set GALACTICA to 0.
=> set base fee if GALACTICA forks from 0

.git-hooks/pre-commit, Makefile
This PR adds a hook to git that prevents the commit of pks.
- Adds a `make install-hooks` step to the Makefile
- Registers the .git-hooks/precomit to the .git config
- Everytime a pk gets committed it fails to commit
- If the pks are correctly committed `git commit --safe-to-ignore-key` should be used to bypass the check
=> Adding a git hook that prevents pks from being committed

.git-hooks/pre-commit
Git pre-hook now uses an Env variable to skip check.
=> Update git hook to use env var instead of flag

builtin/staker/delegations.go, builtin/staker/delegations_test.go, builtin/staker/staker.go
Fix so we can subtract the delegator stake from a queued validator since housekeeping does not apply to queued validators.
Required to complete https://github.com/vechain/protocol-board-repo/issues/623.
=> fix: queued stake for delegations

cmd/thor/sync_logdb.go
This is a low-priority task.
Changes the verification of the log db from using the reflect package to using statically typed validation.
Moving to statically typed checks reduces the checks in 2 orders of magnitude.
Will also run this locally to check for errors / results.
Gist for benchmark here: https://gist.github.com/otherview/3db56b838d840559100b5b024d4dcf00
Results
```
goos: darwin
goarch: arm64
pkg: github.com/vechain/thor/v2/cmd/thor
cpu: Apple M3
BenchmarkEventComparison_ReflectDeepEqual_Small
BenchmarkEventComparison_ReflectDeepEqual_Small-8       	 8635862	       120.5 ns/op	      48 B/op	       2 allocs/op
BenchmarkEventComparison_StaticTyped_Small
BenchmarkEventComparison_StaticTyped_Small-8            	626343638	         1.894 ns/op	       0 B/op	       0 allocs/op …
```
=> Use static type checking vs reflect.DeepEqual

builtin/staker/housekeeping.go, builtin/staker/staker_test.go
Fixing the queuedWeight changes and add test that increases and then decreases a validator's stake during two stake periods
=> Decrease stake weight

.github/workflows/on-pull-request.yaml, .github/workflows/test-rosetta.yaml
The Rosetta repo builds a Docker image using the Thor codebase. This means that if there was a PR coming from a fork, we were just taking the commit from Thor's feature branch (falling back to the default commit if error), rather than the commit from the Thor's fork.
This PR fixes that. Closes https://github.com/vechain/protocol-board-repo/issues/654.
PS: I created it from my own fork to test it. Related logs from the execution of the checks:
```
#26 [rosetta-server thor-builder 3/3] RUN git clone https://github.com/freemanzMrojo/thor.git . &&     git checkout 5131b64230fbc191829b8a4e45589c04f5d6205b &&     make all
#26 0.163 Cloning into '.'...
#26 2.455 Note: switching to '5131b64230fbc191829b8a4e45589c04f5d6205b'.
```
=> fix(gha): fork repo for rosetta

api/accounts/accounts.go, api/rewards/rewards.go, builtin/energy/energy.go, builtin/energy/energy_test.go, builtin/native_calls_test.go, builtin/prototype_native.go, consensus/consensus.go, consensus/validator.go, packer/packer.go, runtime/runtime.go, runtime/runtime_test.go, state/account.go, state/state.go, state/state_test.go, thor/params.go, tracers/native/prestate.go, txpool/tx_pool.go
To have a clean view of `state`. And let `builtin.Energy.Native` to handle the energy growth stop.
=> move energy growth stop time from state to energy

builtin/solidity/uint256.go, builtin/staker/delegations.go, builtin/staker/delegations_test.go
fix: aggregations weights were not reduced, so validators total weight would be higher than they should be and never get reduced
=> fix: reduce aggregation pending weights on withdraw

thorclient/bind/bind_test.go, thorclient/bind/call.go, thorclient/bind/contract.go, thorclient/bind/filter.go, thorclient/bind/method.go, thorclient/bind/send.go, thorclient/builtin/authority.go, thorclient/builtin/energy.go, thorclient/builtin/executor.go, thorclient/builtin/params.go, thorclient/builtin/prototype.go, thorclient/builtin/staker.go, thorclient/builtin/staker_test.go
bind -> return structs instead of interfaces (https://bryanftan.medium.com/accept-interfaces-return-structs-in-go-d4cab29a301b)
=> chore(bind): return structs instead of interfaces

builtin/staker/aggregation/aggregation.go, builtin/staker/delegations_test.go, builtin/staker/staker.go, builtin/staker/validation/service.go, builtin/staker/validation/validation.go, builtin/staker/validations_test.go, consensus/poa_validator.go, consensus/poa_validator_test.go
This PR updates minor items in the staker package, namely:
- Adds missing comments
- Simplifies some calculations
- Adds a GetExistingValidation that contains the isEmpty check
- Moves the GetWithdrawable to a property in the validator struct
- `validation.NextPeriodDecrease` is now `PendingUnlockVET`
- `valdiation.PendingLocked` is now `QueuedVET`
Fixes # [(issue)](https://github.com/vechain/protocol-board-repo/issues/610)
=> Cleanup staker ops

builtin/staker_native_pause_test.go
Update `staker_native_pause_test.go`.
Remove `staker.ActivateNextValidator` function because it will chanage to private.
=> Update Pause test code

builtin/staker/aggregation/aggregation.go, builtin/staker/delegations_test.go
Removed ExitingVET check on `exit` and added a proposed test for it.
An error was only triggered if a delegator and validator were exiting at the same time, if this happens - the check is not required, as a validator exit will set ExitingVET and ExitingWeight to 0
Fixes https://github.com/vechain/protocol-board-repo/issues/733
Tested with existing unit tests and added an additional unit test
=> remove ExitingVET check

builtin/staker/delegation/service.go, builtin/staker/staker.go, builtin/staker_native_gas_test.go
As per title. This PR ensures the delegation services are decoupled from the validation object.
Also applied minor fixes like removing the extra delegation get in the withdraw method.
Fixes # [(issue)](https://github.com/vechain/protocol-board-repo/issues/731)
=> Uncouple Delegation Service SignalExit from Validation

.github/workflows/on-pre-release.yaml, .github/workflows/on-release.yaml, .github/workflows/release-binaries.yaml, .gitignore, tracers/logger/logger.go, tracers/native/call.go, tracers/native/prestate.go
- Publish thor binaries on release. See example here: https://github.com/darrenvechain/thor/releases/tag/v2.3.1
- Optionally publish disco binaries as well (on demand rather than automatic)
- Not using goreleaser as it doesn't play well with parallel builds. It expects to build all binaries at once. Cross arch build not possible with thor
=> feat: publish binaries to release

builtin/staker/delegations_test.go, builtin/staker/housekeep.go, builtin/staker/protocol.go, builtin/staker/staker.go, builtin/staker/staker_test.go, builtin/staker/transition.go, builtin/staker/validation/service.go, builtin/staker/validations_test.go, consensus/consensus.go, consensus/pos_validator.go, consensus/pos_validator_test.go, consensus/validator.go, genesis/devnet.go, packer/packer.go, packer/pos_scheduler.go
- removes duplicated logic from `packer` and `consensus` to inside staker package
- don't return leadergroup from housekeeping, only a bool indicating if it needs to
=> refactor(staker): move trasition, housekeeping and status check to staker

builtin/staker/delegation/delegation.go, builtin/staker/delegation/delegation_test.go, builtin/staker/delegation/service.go, builtin/staker/delegations_test.go, builtin/staker_native.go
This PR is another solution for https://github.com/vechain/thor/pull/1297, have talked with stargate team. They'll firstly get delegation status from `getDelegation` check stake first. And we'll make sure isLocked always return false when there is no stake.
=> add delegation.islocked

builtin/staker/delegation/service.go, builtin/staker/delegation/service_test.go, builtin/staker/delegations_test.go, builtin/staker/staker.go, builtin/staker/staker_test.go, builtin/staker/validation/service.go, builtin/staker/validation/service_test.go, builtin/staker/validations_test.go, builtin/staker_native.go, builtin/staker_native_gas_test.go, pos/sched_test.go, xenv/revert.go
Limits the error checking in the first space, also moved error check test from service to staker tests.
=> move reverts error from services to staker

builtin/staker/aggregation/aggregation.go, builtin/staker/aggregation/aggregation_test.go, builtin/staker/aggregation/service_test.go, builtin/staker/globalstats/delta.go, builtin/staker/globalstats/delta_test.go, builtin/staker/globalstats/service.go, builtin/staker/globalstats/service_test.go, builtin/staker/staker.go, builtin/staker/staker_test.go, builtin/staker/stakes/stakes.go, builtin/staker/validation/service.go, builtin/staker/validation/service_test.go, builtin/staker/validation/validation.go, builtin/staker/validation/validation_test.go, builtin/staker/validations_test.go
Also
- Included `exsitingVET` in aggregations
- Reworked version of `Validation.Totals`
=> clean up queued stake to use uint64

tracers/logger/logger.go, tracers/logger/logger_test.go
Using `hex.EncodeToString` instead
=> chore: small optimization when encoding hex to string

cmd/thor/main.go, cmd/thor/node/node.go, cmd/thor/node/node_benchmark_test.go
Small tweak for the node to use `PackerEngine` and `ConsensusEngine` interfaces in the node instead of structs.
Fixes # [(issue)](https://github.com/vechain/otherviews-workboard/issues/204)
=> Use PackerEngine and ConsensusEngine interfaces in the node

builtin/staker/globalstats/service.go, builtin/staker/housekeep.go, builtin/staker/staker.go, builtin/staker/staker_test.go, builtin/staker/validation/service.go, builtin/staker_native_test.go
Delegations are no longer allowed to validations that have signaled exit.
=> No delegations when exiting validator

builtin/staker_native.go, builtin/staker_native_gas_test.go
Removing a redundant gas consumption call when PoS is not yet active since `Authority.Native(env.State()).Get(thor.Address(args.Validator))` is actually charging the same amount of gas for the same operation.
Fixes [GHIssue](https://github.com/vechain/protocol-board-repo/issues/858)
=> Remove redundant gas consumption call
