comm/sync.go

fix: panic on block syncing

---

api/accounts/accounts.go
api/events/events.go
api/transactions/transactions.go
api/transfers/transfers.go
cmd/thor/must.go
cmd/thor/utils.go

fix(API): limit http request body size within 96kb

---

.gitmodules

in case of failure of `dep ensure`

add vendor folder

---

api/accounts/types.go

fix:encode vm output data into hex string directly whether or not  a vm error occured

---

cmd/thor/main.go

to prevent hanging on exiting #57

fix(cli): close http server instead of gracefully shutdown

---

api/accounts/accounts.go

feat(API): timeout by adding accounts call context

---

cmd/thor/node/node.go
cmd/thor/solo/solo.go
comm/txs_loop.go
txpool/tx_pool.go
txpool/tx_pool_test.go

always broadcast TxEvent when tx added without error

feat(txpool): use bool pointer to present tx status

---

cmd/thor/node/node.go

fix(node): panic in txStashLoop

---

README.md

As a native English speaker and someone who is new to Docker, this section was a bit confusing to me and took a little bit to figure out. Hopefully, this adds some clarity for other users.

Updated the docker readme with less confusing english

---

cmd/thor/flags.go
cmd/thor/main.go
cmd/thor/must.go
genesis/privatenet.go

**genesis.json**
``` JSON
{
"launchTime": 1530316800,
"gasLimit": 10000000,
"extraData": "vechain thor",
"accounts": [{
"address": "0x137053dfbe6c0a43f915ad2efefefdcc2708e975",
"balance": 25000000000000000000000000,
"energy": 21046908616500000000000000000,
"code": "0x606460",
"storage": {
"0x0000000000000000000000000000000000000000000000000000000000000001": "0x000000000000000000000000000000000000000000000000000000000000000222"
}
}, {
"address": "0xaf111431c1284a5e16d2eecd2daed133ce96820e",
"balance": 25000000000000000000000000,
"energy": 21046908616500000000000000000
}, {
"address": "0x997522a4274336f4b86af4a6ed9e45aedcc6d360",
"balance": 25000000000000000000000000,
"energy": 21046908616500000000000000000
}, {
"address": "0x0bd7b06debd1522e75e4b91ff598f107fd826c8a",
"balance": …
```

Custom genesis support

---

runtime/runtime.go
thor/fork_config.go

Change ChainConfig according to ForkConfig.
Testing:
Activation of forkconfig tested on solo mode.

Modify Runtime to Include ForkConfig

---

cmd/thor/flags.go
cmd/thor/main.go
txpool/blocklist.go
txpool/tx_pool.go

to block txs originated from addresses in blocklist

txpool: add blocklist ability

---

cmd/thor/flags.go
cmd/thor/main.go
cmd/thor/solo/solo.go

- Add 2 flags.
- Improve Skiplogs on Solo mode.

Entropy Branch: Improve solo mode ability

---

block/header.go
consensus/validator.go
packer/packer.go
poa/backer.go
poa/sched.go
poa/sched_test.go
poa/seed.go
thor/fork_config.go
thor/params.go

https://gist.github.com/laalaguer/924cef55ed17ad49a0d62ef09b130b0f

 poa: add seeder for leader selection

---

go.mod
go.sum

which accelerates table compaction and reduces the chance of stuck during high write load

upgrade leveldb

---

block/header.go
state/account.go
thor/hash.go
thor/hash_test.go
trie/hasher.go
trie/node.go
tx/transaction.go

This PR eliminates allocs when calling thor.Blake2b and adds new function thor.Blake2bFn.

Improve hash

---

block/extension.go

improve block encoding, reject unexpected extension

---

.github/workflows/test.yaml

update ci syntax and golang to latest version

---

README.md

Also remove broken link from ToC

doc: add hint of docker default user's change

---

api/doc/thor.yaml

@libotony just stumbled over a typo during testing of the upgrades

Fix typo in docs

---

tx/clause_test.go
tx/receipt_test.go
tx/transaction_test.go
tx/transactions_test.go
tx/work_eval_test.go

This PR closes [this issue](https://github.com/vechainfoundation/protocol-board-repo/issues/20) by increasing the coverage of all files above 80%. @libotony Can you please review?

Add tx package tests

---

state/stage_test.go
state/state_test.go
state/stater_test.go

This PR closes the [following issue](https://github.com/vechainfoundation/protocol-board-repo/issues/28) by increasing the coverage of all files above 80%

Add tests for state package

---

.github/CODEOWNERS

When this gets merged, we can add this setting:
`Require review from Code Owners`

adding code owners

---

packer/flow_test.go
packer/packer_test.go

Adds code coverage tests to packer module to reach >=80%
Fixes # 34
Adds tests
`make test-coversage`

Adds code coverage tests to packer

---

.github/ISSUE_TEMPLATE/config.yml
README.md

Update readme to include docker compose example and fix broken discord link
N/A

fix: discord link and add compose example

---

kv/bucket_test.go

`bucket.go` from 30.30% to 93.9%
`f.go` from 10.53% to 52.6%
Addresses [#25](https://github.com/vechain/protocol-board-repo/issues/25)

Increase kv package coverage

---

go.mod
go.sum

- Upgrades geth dependency for the latest commit of `thor-upstream`
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Go Version:
* Hardware:

Update geth for p2p

---

api/doc/thor.yaml

Fix `thor.yaml` -> `required` field was used incorrectly
Imported the new version into: https://editor.swagger.io/

fix: thor.yaml

---

Dockerfile
go.mod
go.sum
logdb/logdb.go

Reverts the docker build image & sqlite chages 
- Unit tests

refactor: using old sqlite version

---

.github/CONTRIBUTING.md
.github/pull_request_template.md
README.md

Update contributing guidelines
git commit

chore: update contributing docs

---

.github/workflows/on-release.yaml

Fix official release
Check pre-release action

fix docker release action

---

api/subscriptions/beat2_reader_test.go
api/subscriptions/beat_reader_test.go
api/subscriptions/block_reader_test.go
api/subscriptions/event_reader_test.go
api/subscriptions/pending_tx_test.go
api/subscriptions/subscriptions.go
api/subscriptions/subscriptions_test.go
api/subscriptions/transfer_reader_test.go
api/subscriptions/types_test.go
txpool/tx_object.go
txpool/tx_pool.go

Added `api/subscriptions` tests, increasing the coverage to 82.2%.

Subscriptions test

---

api/debug/debug.go
api/debug/debug_test.go
tracers/tracers.go

Added tests for the `api/debug` packages. With this test suite its coverage is 86.7%.

Debug test

---

api/utils/http_test.go

This commit adds a test coverage suite for the `api/utils` package.

test: add test coverage for api/utils package

---

.github/workflows/on-master-commit.yaml
.github/workflows/on-pull-request.yaml
.github/workflows/test-e2e.yaml

This PR enables E2E Testing
See the GitHub action result

Enable e2e tests

---

txpool/tx_pool_test.go

Removed unnecessary time.sleep functions and improved coverage.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

improve txpool tests

---

cmd/thor/optimizer/optimizer_test.go

Tests for cmd/noe/optimizer
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

add tests for cmd/node/optimizer

---

README.md
docs/hosting-a-node.md
docs/usage.md

improve doc, add genesis flag to solo

---

.github/workflows/test.yaml

Seems tokenless upload for codecov does not working for us anymore, trying the v4 one

switch codecov action to v4

---

.github/workflows/on-pull-request.yaml
cmd/thor/flags.go

Fixes vechain/protocol-board-repo#179

set solo's default gaslimit to 40M

---

.github/workflows/license-check.yaml
.github/workflows/on-master-commit.yaml
.github/workflows/on-pull-request.yaml
.licenserc.yaml
Makefile
thor/blocklist_test.go
thor/fork_config_test.go
thor/receipt_correction_test.go
trie/derive_root_test.go

This changes introduce a GHA to check for licenses on all go files
Locally, by running:
```
make license-check
```

add GHA to check for license

---

.github/ISSUE_TEMPLATE/config.yml
README.md
docs/hosting-a-node.md

Add repo badges. See example here: https://github.com/darrenvechain/thor/tree/add-repo-badges

feat: add repo badges

---

.github/workflows/on-master-commit.yaml

Fix master commit message
Test:
- Commit: https://github.com/darrenvechain/thor/commit/026b66357b6f715f10955e066bb8b2446511af76
- PR: https://github.com/darrenvechain/thor/pull/34
- Run: https://github.com/darrenvechain/thor/actions/runs/9110005907/job/25044082976

fix: master commit message

---

api/doc/thor.yaml

Add thor.yaml notes for examples

fix: add a note to specify mainnet optimization

---

bft/engine.go
bft/metrics.go
cmd/thor/node/metrics.go
cmd/thor/node/node.go
cmd/thor/node/packer_loop.go
txpool/tx_pool.go

tweak metrics in txpool and node

---

cmd/thor/solo/solo.go
cmd/thor/solo/solo_test.go

adapt shutdown signal in solo init function

---

cmd/thor/flags.go
cmd/thor/main.go
cmd/thor/p2p/p2p.go
cmd/thor/utils.go

minor comment improvement in package cmd/thor

---

metrics/prometheus_test.go

Fixes https://github.com/vechain/protocol-board-repo/issues/211

Provide some time for test to ingest metrics

---

metrics/prometheus_test.go

Fixes https://github.com/vechain/protocol-board-repo/issues/211 
Removed the http server from the test.

Removes http server from the prom test

---

metrics/prometheus_test.go

Fixes # https://github.com/vechain/protocol-board-repo/issues/211

Fix prometheus test race condition

---

cmd/thor/utils.go
metrics/noop_test.go
metrics/prometheus_test.go

Build was broken after some auto merges.
This fixes it.

Fixes the build

---

codecov.yml

This PR introduces the codecov.yml file in which we can include the files we want to ignore from code coverage.
Fixes [194](https://github.com/vechain/protocol-board-repo/issues/194)
Codecov now considers the `codecov.yml` file which includes a list of files to be ignored.
N/A

Configure codecov ignored files

---

cmd/thor/node/node.go

node: fix block metric label

---

docs/build.md

doc: add release hint for build from source

---

.github/workflows/go-mod-check.yaml
.github/workflows/lint-go.yaml
.github/workflows/on-release.yaml
.github/workflows/test-e2e.yaml
.github/workflows/test.yaml

Update all workflow action versions

chore: use latest workflow versions

---

consensus/consensus_test.go

Addresses [this](https://github.com/vechain/protocol-board-repo/issues/231)

Increase consensus coverage to +85%

---

.github/workflows/on-master-commit.yaml

fix: master CI notification

---

cmd/disco/flags.go
cmd/disco/main.go
cmd/disco/utils.go
cmd/thor/main.go
cmd/thor/p2p/p2p.go
cmd/thor/utils.go
metrics/prometheus.go
trie/proof.go
trie/trie.go

+ Use root logger in pkg cmd
+ Added a level filter to eth logger
+ Apply new logger to minor pkg
+ Apply unit flag to verbosity

minor: improve logging

---

.github/workflows/test-e2e.yaml

chore: update thor e2e for reliability

---

api/utils/revisions.go
bft/engine.go
cmd/thor/node/node.go
cmd/thor/node/packer_loop.go
cmd/thor/solo/types.go

This PR used a non-persist way to implement feature justified, which have two improvements of the original PR:
- Works right away after upgrade(Original implement needs to wait for one epoch to be concluded)
- No need to handle soft fork
This is a draft, tests need to be updated

a non-persist way to implement jutified

---

.github/ISSUE_TEMPLATE/feature-request.yaml

Add a new issue template to allow creation of feature requests/ enhancements
See https://github.com/darrenvechain/thor/issues/new/choose

chore: add feature issue template

---

.github/workflows/lint-go.yaml
.golangci.yml
cmd/thor/sync_logdb.go
comm/communicator.go
comm/sync.go
comm/txs_loop.go
tracers/logger/logger.go

Update golangci-lint to 1.60.3.
Updates the gh action too.
Fixes # [(issue)](https://github.com/vechain/protocol-board-repo/issues/306)

Update golangci-lint to update gosec

---

api/doc/thor.yaml

reset current release to v2.1.4

---

api/admin.go
api/admin_server.go
api/admin_test.go
cmd/thor/flags.go
cmd/thor/main.go
cmd/thor/utils.go

leverage api uitls in admin server

---

.github/workflows/lint-go.yaml
api/accounts/accounts_test.go
api/blocks/blocks_test.go
api/events/events_test.go
api/node/node_test.go

It looks like the thor client merge got away with passing some linter issues to the master code.
This mainly happened because the `only-new-issues` was active.
The fix is to guarantee the `only-new-issues` is deactivated.
Fixes # [(issue)](https://github.com/vechain/otherviews-workboard/issues/106)

Show all issues on lint

---

docs/hosting-a-node.md

Reduce over spec'd hardware. Also change public node to `Validator`. We can't make recommendations for an unknown amount of API calls.

chore(docs): update spec for validator nodes

---

logdb/sequence.go
logdb/sequence_test.go

A safety precaution for a successor who is willing to get hands dirty to the sequence.go file.

add safety guard to the sequence

---

cmd/thor/node/node_benchmark_test.go
test/testchain/chain.go

Benchmark tests for Node Block Process.
Fixes # [(issue)](https://github.com/vechain/otherviews-workboard/issues/112)

Add benchmark test to node block process

---

api/transactions/transactions_benchmark_test.go

Adds a benchmark for getting Tx and getting receipts
Fixes # [(issue)](https://github.com/vechain/otherviews-workboard/issues/114)

Add GetTx GetReceipts Benchmark

---

cmd/thor/main.go

fix: solo start flags

---

chain/cache.go
chain/metrics.go
chain/repository.go

chore(chain): add repo cache metrics

---

.github/workflows/test-e2e.yaml

- update test commit sha
- maintenance of tests
- local and before PR test runs

chore(e2e): test updates

---

.github/workflows/publish-docker-images.yaml

Publish the latest readme with the latest docker tag

chore(dockerhub): update description on release

---

cache/stats.go
cache/stats_test.go
chain/repository.go
muxdb/internal/trie/cache.go

chore(stats): move cache stats to cache package

chore(stats): move cache stats to cache package

---

.github/workflows/on-pull-request.yaml

The PR GH actions will run on every branch.

chore: run PR actions on every branch

---

.github/workflows/gosec.yaml

fix(gha): remove extra comma

---

test/testchain/chain.go

fix gosec linting

---

.github/workflows/publish-docker-images.yaml

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List
any dependencies that are required for this change.
* Go Version:
* Hardware:

Run on older version of runner

---

cmd/thor/node/metrics.go
cmd/thor/node/node.go

This ensures all forks are captured. Gauges may not be caught by the time they go back down to 0

chore(metrics): update the fork counter

---

.github/workflows/on-master-commit.yaml

Publish release branches internally on github on commit to `release/*`

chore(gha): publish release branches to github on commit

---

.github/workflows/on-master-commit.yaml

fix: broken master CI

---

api/subscriptions/subscriptions.go
api/utils/http.go

Ensures errors are surfaced correctly, handles errors in the websocket connections correctly.

Enhance err handling in websockets

---

api/events/types.go
api/events/types_test.go

fix: using from instead of to

---

thorclient/wsclient/client.go

Allows the use of the RawWS connection of thorclient.
Similar to the RawHTTP connection usage.
Particularly useful for the duplication traffic smoke test.
Fixes # [(issue)](https://github.com/vechain/protocol-board-repo/issues/405)

thorclient WS Raw Connect Public

---

Makefile

`clean` now cleans everything and `clean-bin` is the former `clean`

chore(Makefile): refactored `clean` and added `clean-bin`

---

co/signal.go
co/signal_test.go

Removed method `Signal` that is not used. Adapted unit tests accordingly.

chore(`co`): removed unused method `Signal`

---

thorclient/api_test.go
thorclient/httpclient/client.go
thorclient/httpclient/client_test.go
thorclient/thorclient.go

thorclient implementation of the `fees/history` endpoint.
Addresses https://github.com/vechain/protocol-board-repo/issues/416

feat: `fees/history` client

---

.github/workflows/lint-go.yaml
builtin/native_calls_test.go

Add expected gas usage tests for extension v2

chore: add gas usage test for extension

---

README.md

Update readme URLs: https://github.com/vechain/thor/tree/darren/chore/update-readme

chore: update image urls in readme

---

api/blocks/types.go

Add tx type to expanded block txs

fix: add tx type to expanded block

---

api/transactions/transactions_converter.go
api/transactions/transactions_coverter_test.go

Consistent types on txs, this matches expanded block TXs

chore: consistent types for tx type

---

metrics/telemetry.go

chore(metrics): deleted unused `NoOp()` method

---

block/block.go
thor/size.go
tx/transaction.go

change storagesize to uint64

---

Makefile
block/block_test.go
block/header_test.go
runtime/resolved_tx.go
tx/transaction_test.go
tx/tx_dynamic_fee.go
txpool/validation.go
txpool/validation_test.go

This PR introduces fuzz testing for transaction, block and header encoding/decoding.
[GHIssue](https://github.com/vechain/protocol-board-repo/issues/464)

Fuzz tests

---

api/node/node_test.go
cmd/thor/flags.go
cmd/thor/main.go

Increases limit per account to 128 tx's
* Go Version:
* Hardware:

Increase limit per account

---

.licenserc.yaml
logdb/logdb.go
logdb/metrics.go

Add metrics for event query params

chore(metrics): add logDB filter metrics

---

README.md

chore: update evm version in readme

---

api/transactions/types_test.go
api/transfers/transfers_test.go
cmd/thor/utils.go
logdb/logdb_test.go
runtime/runtime.go
trie/derive_root.go
trie/derive_root_test.go
tx/receipt.go
tx/receipt_test.go
tx/transactions.go

Also updated the DerivableList interface to reflect the recent encoding change.

flat fields in receipt

---

api/blocks/types.go

Change gasPriceCoef type in tx expanded block response body

change gasPriceCoef type in expanded block response body

---

api/doc/thor.yaml

fix: types in thor.yaml

---

api/subscriptions/block_reader_test.go
api/subscriptions/types.go

Add baseFeePerGas to block subscription response
[GHIssue](https://github.com/vechain/protocol-board-repo/issues/526)

Add baseFeePerGas to block subscription response

---

api/doc/thor.yaml
api/subscriptions/beat2_reader.go
api/subscriptions/types.go

Adds the baseFeePerGas to beat2 response body
[GH Issue](https://github.com/vechain/protocol-board-repo/issues/536)

Add baseFeePerGas to beat2 response body

---

api/doc/thor.yaml

As per title
[GH-Issue](https://github.com/vechain/protocol-board-repo/issues/543)

Add reference to transaction model documentation

---

consensus/fork/galactica.go
tx/transaction.go

Adding a comment regarding division by zero pre-check
* Go Version:
* Hardware:

Add comment

---

vm/stack.go

Update stale comment.
* Go Version:
* Hardware:

Add comment about the stack depth enforcement

---

txpool/tx_object.go
txpool/tx_object_test.go

If the price is equal sort by time added
* Go Version:
* Hardware:

Sort by price and timeAdded

---

logdb/logdb.go
logdb/types.go

Revert query optimization.
* Go Version:
* Hardware:

Minor improvement

---

consensus/consensus_test.go
consensus/validator.go
packer/flow.go
packer/flow_test.go
txpool/tx_pool.go

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List
any dependencies that are required for this change.
* Go Version:
* Hardware:

Re-organise

---

api/fees/fees_test.go
genesis/devnet.go
test/testchain/chain.go
tx/transaction_test.go
txpool/tx_pool_test.go

fix lint and test

---

api/fees/fees_test.go

Adds a test for large blockcount numbers

Add uint64 fee test

---

api/utils/revisions_test.go
thor/fork_config.go

use thorchain's forkconfig in revsion test

---

api/fees/data.go
api/fees/data_test.go

This PR changes the `fees/history` endpoint to no longer return/process rewards field pre-Galactica hardfork.
The `fees/history` returns information about blocks and in particular about the rewards in the blocks.
The rewards refer to priority fees per gas, which are different from pre-Galactica validator rewards.
Added a test that showcases pre and post Galactica rewards .

Only return priority rewards for post-galactica

---

.github/workflows/on-master-commit.yaml
.github/workflows/on-pull-request.yaml
.github/workflows/test-rosetta.yaml

Rosetta e2e tests over a Solo network.
Closes https://github.com/vechain/protocol-board-repo/issues/367.

chore: rosetta solo e2e tests

---

.github/workflows/on-master-commit.yaml
.github/workflows/on-pull-request.yaml
.github/workflows/test-e2e.yaml

fix: only send slack messages for master failures

---

.github/workflows/test-e2e.yaml
.github/workflows/test-rosetta.yaml

Using fallback commit/branch for external repos (e2e, rosetta).

chore: fallback commit/branch for external repos

---

builtin/staker/delegations.go
builtin/staker/delegations_test.go
builtin/staker/storage.go
builtin/staker/types.go
builtin/staker/validations.go
builtin/staker_native.go

bug(delegations): first iteration is set incorrectly

---

api/accounts/accounts.go
api/accounts/accounts_test.go
api/accounts/types.go
thorclient/httpclient/client_test.go

using pointers for account balances

fix: use pointers for account balances

---

api/fees/data.go
api/fees/fees.go
api/utils/revisions.go
consensus/consensus_test.go
consensus/upgrade/galactica/galactica.go
consensus/upgrade/galactica/galactica_test.go
consensus/validator.go
consensus/validator_test.go
packer/flow.go
packer/flow_test.go
packer/packer.go
runtime/resolved_tx.go
runtime/runtime.go
txpool/tx_object.go
txpool/tx_pool.go
txpool/tx_pool_test.go
txpool/validation.go
txpool/validation_test.go

rename package fork to upgrade

---

api/accounts/accounts.go
api/accounts/accounts_test.go
api/accounts/types.go
api/events/events.go
api/events/events_test.go
api/events/types.go
api/transfers/transfers.go
api/transfers/transfers_test.go
api/transfers/types.go
thorclient/api_test.go
thorclient/thorclient.go

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List
any dependencies that are required for this change.
Fixes [vechain/protocol-board#612](https://github.com/vechain/protocol-board-repo/issues/612)

api: reject request body with null in slice

---

cmd/thor/solo/solo.go
test/testsolo/solo.go

- Added new `test/testsolo` package with Solo struct for simplified solo node testing
- Renamed `packing` to `PackNewBlock` in `cmd/thor/solo/solo.go` to allow code-driven block creation
Fixes # [(issue)](https://github.com/vechain/otherviews-workboard/issues/181)

Adding testsolo package

---

logdb/logdb.go

- Optimized in-memory SQLite database configuration in `logdb/logdb.go` for better test performance
- Optimized SQLite settings in `logdb/logdb.go` for in-memory operations:
- `synchronous=OFF`
- `journal_mode=MEMORY`
- `cache_size=-2000`
- `temp_store=MEMORY`

Improve logdb inmem

---

consensus/upgrade/galactica/galactica.go
consensus/upgrade/galactica/galactica_test.go
runtime/resolved_tx.go
runtime/runtime.go
runtime/runtime_test.go
tx/transaction.go
tx/transaction_test.go
tx/tx_dynamic_fee.go
tx/tx_legacy.go
txpool/tx_object_map_test.go

This PR introduced the concept `EffectiveGasPrice` to tx package and moved the logic from fork package to tx package.

add effectiveGasPrice in tx

---

api/node/node.go
api/transactions/transactions.go
api/transactions/transactions_converter.go
api/transactions/transactions_coverter_test.go

Removes duplicated code from convertTransaction
* Go Version:
* Hardware:

Remove duplicated code

---

txpool/tx_pool.go
txpool/tx_pool_test.go

Fix tx pool metrics
* Go Version:
* Hardware:

fix tx pool metric recording

---

builtin/staker/validations.go

As per title 
Fixes # [(issue)](https://github.com/vechain/protocol-board-repo/issues/610)

Add auto-renew check + rework conditions

---

.github/workflows/gosec.yaml
.github/workflows/license-check.yaml
.github/workflows/publish-docker-images.yaml
.github/workflows/test-e2e.yaml
.github/workflows/test-rosetta.yaml
.github/workflows/test.yaml

update workflow permissions

---

go.mod
go.sum

Includes PR vechain/go-ethereum#14
Fixes vechain/otherviews-workboard#135

update dependency go-ethereum

---

pos/sched_test.go

chore(pos): add a 🐳 distribution test case

---

builtin/staker/staker_test.go

chore(staker): add a unit test for decrease -> exit -> withdraw

---

builtin/staker/delegations.go
builtin/staker/delegations_test.go
builtin/staker/housekeeping.go
builtin/staker/staker.go
builtin/staker/types.go
builtin/staker/validations.go
builtin/staker/validations_test.go

fix(staker): various increase/decrease/renew test cases

---

api/rewards/rewards_test.go
builtin/energy/energy.go
builtin/energy/energy_test.go
builtin/native_calls_test.go
runtime/runtime.go
thor/params.go

Replace ScalingFactor and TargetFactor with a single value
[Ticket](https://github.com/vechain/protocol-board-repo/issues/621)

Introducing Curve factor param

---

thorclient/bind/send.go

chore(bind): add depends on tx option

chore(bind): add depends on tx option

---

bft/engine_poa_test.go
bft/engine_pos_test.go

Refactor engine tests for poa and pos based on this [PR](https://github.com/vechain/thor/pull/1183). The two files are testing finality in the two different consensus.

refactor tests on finality

---

builtin/energy/energy.go
builtin/energy/energy_test.go
thor/params.go

Add ValidatorRewardPercentage param as per [github ticket](https://github.com/vechain/protocol-board-repo/issues/621).

Add ValidatorRewardPercentage param

---

builtin/staker/delegation/service.go
builtin/staker/staker.go
builtin/staker/validation/service.go
builtin/staker_native_gas_test.go

Reduce read operations for some staker functions

chore(staker): reduce read ops

---

cmd/thor/utils.go

Master address should be logged in checksum format
* Go Version:
* Hardware:

Show master address in checksum format

---

builtin/staker/delegation/service.go
builtin/staker/delegation/service_test.go
builtin/staker/validation/repository.go
builtin/staker/validation/repository_test.go
builtin/staker/validation/service.go
builtin/staker/validation/service_test.go

Makes SetDelegation and SetValidation private
Fixes # [(issue)](https://github.com/vechain/protocol-board-repo/issues/763)

Private setters

---

cmd/thor/solo/txpool.go
txpool/tx_pool.go

fix(solo): basic tx errors

---

chain/repository.go
chain/repository_test.go
cmd/thor/node/node.go
cmd/thor/node/packer_loop.go

move double signing detaction to post block process hook

---

README.md

Update the banner to use the correct asset path.

Fix README.md Banner

---

builtin/staker/housekeep.go
builtin/staker/staker.go
builtin/staker/validation/service.go
builtin/staker/validation/service_test.go

can't exit if exitblock is set

---

pos/sched.go
pos/sched_test.go

Ticket vechain/protocol-board-repo#799
Also updated the test cases to be close to our scenario.

improve the POS scheduler sampling mechanism

---

builtin/staker/housekeep.go
builtin/staker/staker.go
builtin/staker/validation/service.go
builtin/staker/validation/service_test.go

replace evict method with signalexit

---

builtin/staker/delegation/service.go
builtin/staker/validation/linked_list.go
builtin/staker/validation/linked_list_test.go
builtin/staker/validation/repository.go
builtin/staker/validation/storage.go

Decouples repository into storage and linked list

Reduce linked list iter

---

builtin/staker/doc.go
builtin/staker/validation/service.go
builtin/staker/validation/service_test.go

Also update the way to generate reward by period key, reduced to only one hash.

doc staker contract storage layout

---

bft/engine.go
builtin/staker/staker.go

reject zero address when add validation

---

builtin/staker/globalstats/service.go
builtin/staker/globalstats/service_test.go

Add underflow check
* Go Version:
* Hardware:

Add underflow check

---

thor/params_test.go

Increased coverage by adding a test for `GetMaxBlockProposers`

test: increased coverage

---

cmd/thor/node/packer_loop.go

Ticket vechain/protocol-board-repo#802

improving packer scheduler

---

abi/abi_test.go
block/gas_limit_test.go
builtin/prototype/prototype_test.go
cache/prio_cache_test.go
cache/rnd_cache_test.go
co/goes_test.go
co/parallel_test.go
co/signal_test.go
comm/comm_test.go
genesis/customnet_test.go
genesis/devnet_test.go
genesis/genesis_test.go
genesis/mainnet_test.go
poa/sched_test.go
stackedmap/stackedmap_test.go
thor/bloom/bloom_test.go
thor/bloom/legacy_test.go
thor/hash_test.go
tx/block_ref_test.go
tx/features_test.go
vrf/vrf_test.go

Refactor tests, remove _test from package
* Go Version:
* Hardware:

Refactor tests, remove _test

---

.github/workflows/test-smoke.yaml

fix: draupnir tests `release/hayabusa`

---

builtin/staker/staker.go
builtin/staker/staker_test.go
builtin/staker/validations_test.go

- add some entry level checks for min / max stake values
- fix decrease overflow bug

fix: decrease overflow

---

builtin/staker/staker.go
builtin/staker/staker_test.go
builtin/staker_native_gas_test.go

add withdrawable when decrease in queued status

---

.github/workflows/on-master-commit.yaml

fix: master CI

---

builtin/staker/delegations_test.go
builtin/staker/protocol_test.go
builtin/staker/sequence_test.go
builtin/staker/staker.go
builtin/staker/staker_test.go
builtin/staker/transition_test.go
builtin/staker/validations_test.go

migrate remaining unit tests to v2 of stake

refactor(staker): migrate tests 4

---

builtin/staker/delegations_test.go
builtin/staker/protocol_test.go
builtin/staker/sequence_test.go
builtin/staker/staker.go
builtin/staker/staker_test.go
builtin/staker/transition_test.go
builtin/staker/validations_test.go

refactor(staker): migrate tests 3

---

builtin/staker/delegations_test.go
builtin/staker/protocol_test.go
builtin/staker/sequence_test.go
builtin/staker/staker.go
builtin/staker/staker_test.go
builtin/staker/transition_test.go
builtin/staker/validations_test.go

Finishes all migrations in `validations_test.go`.
TODO:
- delegations
- transition test

refactor(staker): migrate tests to v2

---

builtin/staker/delegations_test.go
builtin/staker/protocol_test.go
builtin/staker/sequence_test.go
builtin/staker/staker.go
builtin/staker/staker_test.go
builtin/staker/transition_test.go
builtin/staker/validations_test.go

migration of more tests to staker v2

refactor(staker): migrate tests

---

builtin/energy/energy.go
builtin/staker_native_gas_test.go

Created tickets instead. Closes https://github.com/vechain/protocol-board-repo/issues/853

chore: removed TODOs

---

genesis/customnet.go
genesis/devnet.go

Params now specify the executor address for solo mode.

Fix hayabusa devnet executor
